// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentConfig():Promise<Record<string, any>>;

export function ReadLogs():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<string>;

export function ToggleProtections(arg1:boolean):Promise<void>;

export function UpdateBannedWords(arg1:string):Promise<void>;

export function UpdateHotkey(arg1:Array<number>):Promise<void>;
