// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function ReadLogs() {
  return window['go']['main']['App']['ReadLogs']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ToggleProtections(arg1) {
  return window['go']['main']['App']['ToggleProtections'](arg1);
}

export function UpdateBannedWords(arg1) {
  return window['go']['main']['App']['UpdateBannedWords'](arg1);
}

export function UpdateHotkey(arg1) {
  return window['go']['main']['App']['UpdateHotkey'](arg1);
}
